studiopress/pattern-manager

wp-modules/pattern-preview-renderer/pattern-preview-renderer.php
WordPress core doesn't use `the_content()` to render block content. Rather it uses [get_the_block_template_html](https://github.com/WordPress/wordpress-develop/blob/d73323e96944a9dbd16ef8edc9c055b1cbc7b735/src/wp-includes/template-canvas.php#L12). By using this instead of `the_content` it means that the block supports get rendered. 
The new Style Engine in WordPress is a long and arduous process to trace through, but this is the end result: using `the_content` means block supports don't work. Using `get_the_block_template_html` means they do. 
Relevant lines of code in WP core (was helpful for debug backtracing to find differences):
https://github.com/WordPress/wordpress-develop/blob/d73323e96944a9dbd16ef8edc9c055b1cbc7b735/src/wp-includes/script-loader.php#L3053
1. Load the Frost theme …
=> Handle block supports by rendering the same way FSE themes do

wp-modules/editor/model.php
Fixes a [bug I introduced](https://github.com/studiopress/pattern-manager/pull/106/files#diff-8ba31aa77fc662d19b7f20a487d3c2e0d83ac9ab99b843479f7ddae96b0649edL131-R133) that prevented editing meta in patterns not created with PM (patterns where the slug doesn't match the title).
I released this bug last week in [0.1.7](https://github.com/studiopress/pattern-manager/releases/tag/0.1.7)
Thanks to Jen and Phil for these
1. Activate [Frost](https://github.com/wpengine/frost) (or most themes with pre-existing patterns)
2. Edit a pattern from the theme (not a pattern you created)
3. Only add a category
4. Save the pattern and reload
5. Expected: The pattern has the category you added:
6. Before this PR: there was nothing in the editor:
Frost didn't cause this bug, it revealed it.
=> Allow saving post meta when the pattern name doesn't match the title (many themes)

README.md, package-lock.json, package.json, pattern-manager.php
Bumps the version for the `0.1.8` release
Not needed
=> Bump the version to 0.1.8

wp-modules/editor/editor.php, wp-modules/editor/utils.php
* Removes a workaround for the Core 'Comments' block
* It's obsolete with https://github.com/studiopress/pattern-manager/pull/152
* The reason for the workaround was to prevent a PHP notice in the preview for the Core 'Comments' block. #152 fixes that.
Not needed
=> Remove obsolete workaround for Core 'Comments' block

wp-modules/editor/js/src/index.js
Brings back the Patternception back for the next release
Not needed
We removed registration of the Patternception block for the last release.
The code is already there, this just brings back registration of the block.
=> Bring back Patternception back for the next release

README.md, package-lock.json, package.json, pattern-manager.php
* Bumps the version to `0.2.0` for the release
Fixes [GF-3789](https://wpengine.atlassian.net/browse/GF-3789)
Not needed
=> Bump the version to `0.2.0`

wp-modules/editor/js/src/components/PatternEdit/index.tsx
Fixes patternception lock icon display problems 
1. Create a pattern using the Pattern Block.
2. Make sure the lock icon is centered within its circle.
Before
After
=> Fix icon not centering

wp-modules/editor/model.php, wp-modules/pattern-data-handlers/pattern-data-handlers.php
Allows saving meta, like Categories, for a new pattern that has no content:
------
Before, the meta didn't save after publishing if there wasn't content: 
Fixes https://github.com/studiopress/pattern-manager/issues/166
See the [To Reproduce steps](https://github.com/studiopress/pattern-manager/issues/166) in PR 166
Pattern saving has become whack-a-mole 😄
=> Allow saving meta for a new pattern with no content

wp-modules/editor/js/src/hooks/usePatternData.ts
Fixes #54.
---
This PR adds the `core/query` block type as a `Transforms (Block Types)` option in the editor sidebar:
---
Other query-related options are currently ignored. All available options are shown below:
=> Make the `core/query` block type available for block transforms

wp-modules/app/js/src/components/Patterns/index.scss
When a pattern preview is by itself, it takes up 100% of the height available. This PR makes it so that it shrinks down to 300px, while still allowing a longer pattern to show its full height. 
I spoke with Kam about this and confirmed that while a masonry layout might be preferable, we can iterate to that later if needed.
1. On main, using the Frost theme, preview your patterns.
2. Click on the "Portfolio" category, where there's only 1 pattern
3. Notice the height of the preview fill all of the available space
4. Change this this branch
5. Refresh and notice the height maxes-out at 300px high, like other previews.
6. Go back to view all patterns, and notice that patterns higher than 300px still show their full height, but shorter pattern beside max-out at 300px, leaving some empty space …
=> Fix pattern preview heights when on a row by themselves

package.json, wp-modules/api-data/tests/ApiDataTest.php, wp-modules/editor/tests/EditorTest.php, wp-modules/editor/tests/UtilsTest.php, wp-modules/get-module-data/tests/PatternManagerGetModuleDataTest.php, wp-modules/get-version-control/tests/GetVersionControlTest.php, wp-modules/pattern-data-handlers/tests/PatternDataHandlersTest.php
In the wp-env project (inside Gutenberg repo), the [PHPUnit and Composer packages were removed](https://github.com/WordPress/gutenberg/pull/50408). 
This resulted in PHPunit tests failing to run using wpp-scripts with the message:
`The 'phpunit' container has been removed. Please use 'wp-env run tests-cli --env-cwd=wp-content/path/to/plugin phpunit' instead.`
In fixing it, I was getting this error:
`PHP Fatal error:  Declaration of PatternManager\PatternDataHandlers\PatternDataHandlersTest::setUp() must be compatible with Yoast\PHPUnitPolyfills\TestCases\TestCase::setUp(): void in /var/www/html/wp-content/plugins/pattern-manager/wp-modules/pattern-data-handlers/tests/PatternDataHandlersTest.php on line 23
`
The fix is to make sure that setUp and tearDown declarations have a void declared …
=> [Dont Merge Yet] Fix PHP unit errors with wp-env phpunit container removal

wp-modules/editor/model.php
I ran into this error when previewing a pattern. Oddly I wasn't able to re-replicate, but adding a check for this is simple. It likely happens during an auto-save procedure in core, and we don't want to do anything on that anyway, so this simply escaped the hook early if that's the case. 
1. Save a pattern. Make sure it works as normal.
=> Make sure post_type exists before using it

wp-modules/editor/js/src/blocks/pattern-block/PatternEdit.tsx
Thanks to Kam for this idea.
Change the 'Replace' button to 'Replace Pattern'
Fixes [GF-3804](https://wpengine.atlassian.net/browse/GF-3804)
1. Create a new pattern
2. Add a Pattern Block
3. Select a pattern
4. Expected: The button says 'Replace Pattern':
=> Chang the 'Replace' button to 'Replace Pattern'

wp-modules/editor/js/src/blocks/pattern-block/PatternEdit.tsx
Mainly pastes Kam's copy into the Patternception Inspector copy
Copy Kam suggested in [GF-3803](https://wpengine.atlassian.net/browse/GF-3803):
>This pattern is being used within the PM Pattern Block in order to create a multi-pattern layout. To edit this pattern, click the button below. Note: Editing this pattern will change it across all instances of this pattern being used in the PM Pattern Block. 
Copy in this PR:
>This pattern is being used within the PM Pattern Block in order to create a multi-pattern layout. Editing this pattern will change it across all instances of this pattern being used in PM Pattern Blocks.
If it's alright, I removed 'To edit this pattern, click the button below.'
There's a lot of copy, and that doesn't add much.
Fixes …
=> Update the Patternception Inspector copy

.distignore
* Add `.nvmrc` and `webpack.config.js` to `.distignore`, so CCI doesn't deploy them to the wp.org SVN repo, and they're not in the `.zip` file
* Download the `.zip` file from the CCI zip job's artifacts
* Unzip it
* Expected: There's no `wp-modules/editor/webpack.config.js`
=> Add some files to `.distignore`

wp-modules/editor/js/src/blocks/pattern-block/PatternEdit.tsx
Adds a tooltip to the lock icon.
See [GF-3802](https://wpengine.atlassian.net/browse/GF-3802)
1. Hover on the lock icon when viewing a pattern inside the Pattern Block.
We may still want to change the icon in the future.
=> Add tooltip to lock

wp-modules/api-data/api-data.php, wp-modules/app/js/src/components/VersionControlNotice/index.tsx, wp-modules/pattern-data-handlers/pattern-data-handlers.php
A much simpler [subset](https://github.com/studiopress/pattern-manager/pull/192/files#r1227497186) of my bloated  https://github.com/studiopress/pattern-manager/pull/192 😄 
Maybe we'll consider https://github.com/studiopress/pattern-manager/pull/192, but if this PR doesn't work, I'll have to rework that.
Phil's [testing steps](https://github.com/studiopress/pattern-manager/pull/192#issue-1744354622)
I couldn't reproduce it, so this PR might not fix it.
=> Don't tree shake in `delete_pattern()`

wp-modules/editor/js/src/blocks/pattern-block/PatternEdit.tsx
Adds the pattern title to the Pattern Block sidebar panel.
Fixes https://wpengine.atlassian.net/browse/GF-3805
1. Add a Pattern Block in the pattern editor.
2. View the information presented in the sidebar. It should show `Pattern` when no pattern is selected yet. Once a pattern is selected, it will display the pattern title.
=> Add pattern title to the Pattern Block sidebar panel heading

wp-modules/editor/js/src/components/SidebarPanels/CategoriesPanel.tsx, wp-modules/editor/js/src/utils/test/validateInput.ts, wp-modules/editor/js/src/utils/validateInput.ts
Previously, typing certain characters could cause issues (up to a whitescreen) when new categories were created in the sidebar UI. This PR adds strict validation as the user types, then strips disallowed characters on `Enter`.
1. Open or create a pattern
2. Try adding a category with non-alphanumeric characters
3. Expected: the disallowed characters should be stripped on `Enter`
A hint is provided by a red border that only appears when disallowed chars are detected. Additionally, the `Create ""` label shown below the input as the new category title is typed has the disallowed characters stripped:
=> Validate new categories on input

wp-modules/editor/js/src/blocks/pattern-block/PatternEdit.tsx, wp-modules/editor/js/src/blocks/pattern-block/registerPatternBlock.ts
Updates the icon for the Pattern Block so it is the same in all areas. Also, updates the sidebar text used for the Pattern Block when no pattern is yet selected.
1. Insert a Pattern Block.
2. Check that the icon is the same per the image below.
3. Check that the sidebar text directs to select a pattern when no pattern is selected.
Before:
After:
=> Update icon, conditionally display sidebar text

wp-modules/app/package-lock.json, wp-modules/app/package.json, wp-modules/editor/package-lock.json, wp-modules/editor/package.json
Bumps `@wordpress/scripts` to the [latest](https://www.npmjs.com/package/@wordpress/scripts/v/26.8.0) to  fix dependabot issues
Fixes [GF-3831](https://wpengine.atlassian.net/browse/GF-3831), [GF-3836](https://wpengine.atlassian.net/browse/GF-3836), [GF-3842](https://wpengine.atlassian.net/browse/GF-3842) 
Not needed
=> Bump `@wordpress/scripts` to fix dependabot issues

wp-modules/pattern-data-handlers/pattern-data-handlers.php, wp-modules/pattern-data-handlers/tests/PatternDataHandlersTest.php
If a theme doesn't have a TextDomain, patterns that have custom categories will have an extra comma in the PHP code, causing a fatal error.
1. Make a theme but have no `TextDomain` in the style.css file
2. Make a pattern with PM and add a custom category to it, and save the pattern.
3. The site should not fatal.
Related: 
https://wordpress.org/support/topic/creating-custom-category-causes-fatal-error/#post-16961268
=> Fix: Remove extra comma which is inserted for themes without a textdomain

wp-modules/app/package-lock.json, wp-modules/app/package.json, wp-modules/editor/package-lock.json, wp-modules/editor/package.json
Remove `postcss` from top-level `devDependencies`, upgrade `@wordpress/scripts`
Fixes [GF-3870](https://wpengine.atlassian.net/browse/GF-3870), [GF-3887](https://wpengine.atlassian.net/browse/GF-3887)
Not needed, I smoke tested the plugin.
=> Remove `postcss` from top-level `devDependencies`, upgrade `@wordpress/scripts`

wp-modules/app/app.php, wp-modules/app/js/src/components/Patterns/PatternGrid.tsx, wp-modules/app/js/src/components/Patterns/PatternGridActions.tsx, wp-modules/app/js/src/types.ts, wp-modules/app/tests/AppTest.php, wp-modules/editor/editor.php, wp-modules/editor/js/src/components/SidebarPanels/ViewportWidthPanel.tsx, wp-modules/editor/js/src/types.ts, wp-modules/editor/model.php, wp-modules/pattern-data-handlers/pattern-data-handlers.php, wp-modules/pattern-data-handlers/tests/PatternDataHandlersTest.php, wp-modules/pattern-preview-renderer/pattern-preview-renderer.php
Adds a nonce when you edit or duplicate a pattern:
Also adds a [nonce to pattern previews](https://github.com/studiopress/pattern-manager/pull/215/files#r1376979717). This is needless, but it could prevent an argument.
1. Go to the Patterns page
2. Click 'Edit' and 'Duplicate'
3. Expected: Those go to the editor
=> Add a nonce to duplicate and edit actions

.eslintrc, pluginade.sh, wp-modules/app/js/src/components/App/index.scss, wp-modules/app/js/src/components/Patterns/PatternGrid.tsx, wp-modules/app/js/src/hooks/useForceRerender.ts, wp-modules/app/js/src/hooks/useLazyRender.ts, wp-modules/editor/js/src/components/Toggles/ModalToggle.tsx, wp-modules/editor/js/src/hooks/usePatternData.ts, wp-modules/editor/js/src/hooks/useSave.ts, wp-modules/editor/js/src/utils/flatUnorderedEquals.ts, wp-modules/editor/js/src/utils/getCustomCategories.ts, wp-modules/editor/js/src/utils/getSelectedOptions.ts
This PR updates to the latest version of Pluginade Scripts, which is 0.0.3. See changelog in https://github.com/pluginade/pluginade-scripts/blob/main/CHANGELOG.md
One big update here is wp-scripts, and using the wp version of prettier.
1. A functional change was made to useForceRender, so check that you can filter which patterns are shown and that they re-render
2. Test general usage of the app.
=> Update to Pluginade 0.0.3
